package Model;
// Generated 29-jun-2019 11:07:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LineasDeVenta generated by hbm2java
 */
public class LineasDeVenta  implements java.io.Serializable {


     private Integer idLinea;
     private String linea;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public LineasDeVenta() {
    }

	
    public LineasDeVenta(String linea) {
        this.linea = linea;
    }
    public LineasDeVenta(String linea, Set<Ventas> ventases) {
       this.linea = linea;
       this.ventases = ventases;
    }
   
    public Integer getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }
    public String getLinea() {
        return this.linea;
    }
    
    public void setLinea(String linea) {
        this.linea = linea;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }




}


