package Model;
// Generated 29-jun-2019 11:07:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private LineasDeVenta lineasDeVenta;
     private Date fechaVenta;
     private String descripcion;

    public Ventas() {
    }

    public Ventas(LineasDeVenta lineasDeVenta, Date fechaVenta, String descripcion) {
       this.lineasDeVenta = lineasDeVenta;
       this.fechaVenta = fechaVenta;
       this.descripcion = descripcion;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public LineasDeVenta getLineasDeVenta() {
        return this.lineasDeVenta;
    }
    
    public void setLineasDeVenta(LineasDeVenta lineasDeVenta) {
        this.lineasDeVenta = lineasDeVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


